Adding option to output json inventory
Stephanevg/psansible.inventory pull request #10
Opened 2023-11-13 13:06 UTC by bateskevin

In order for this module to be used in combination with inventory scripts it would be very usefull to have a json output, that gets accepted by ansible tower. This PR implements this functionality, without introducing breaking changes. Additionally it provides a function to export the ansible inventory at the end, which means it is no longer necessary to call the export method.

2023-11-13 13:52 UTC, Stephanevg commented
@bateskevin  It would be great if you can add a few examples of how it would work to create an inventory in .JSON format.

What would be REALLY cool, is if you can provide an example on how to set it up in tower with a screen shot or two (you can add it on a seperate .md file, which you could link in the main readme.md

2023-11-13 14:06 UTC, bateskevin commented
@Stephanevg I have added examples in your existing docs. For the tower docs I agree that would be cool, but I am afraid we are not quite ready to do it. I can do that once we have set it up completly tho.

2023-11-15 07:59 UTC, Stephanevg requested changes
@bateskevin  I left some comments directly in the code. 
Thanks again for the PR :)

2023-11-15 07:59 UTC, Stephanevg commented on inventory.json
Please don't push your test files in the PR

2023-11-15 07:59 UTC, Stephanevg commented on inventory.ini
Please don't push your test files in the PR

2023-11-15 07:59 UTC, Stephanevg commented on Tests/ansible.inventory.Tests.Ps1
> +        It '[AnsibleInventory] -->  Export-AnsibleInventory : - should return correct inventory structure in json' {
It would make sense to add a bit more 'meat to the bone' by adding a slightly more 'complex' inventory.

2023-11-15 07:59 UTC, Stephanevg commented on Code/Functions/public/Export-AnsibleInventory.ps1
Please add a test case for this function

2023-11-15 07:59 UTC, Stephanevg commented on Demos/Demo01.ps1
Could you add an example of the default outputType (Without passing -OutputType )

2023-11-15 07:59 UTC, Stephanevg commented on README.md
Simplest way would be without the -outputType (defaultvalue would be used)

2023-11-15 07:59 UTC, Stephanevg commented on Tests/ansible.inventory.Tests.Ps1
> +        It '[AnsibleInventory] -->  Export-AnsibleInventory : - should return correct inventory structure in json' {
example of a 'bigger' inventory https://github.com/Stephanevg/psansible.inventory/blob/main/Tests/ansible.inventory.Tests.Ps1#L21C1-L21C1

2023-11-15 07:59 UTC, Stephanevg commented on Tests/ansible.inventory.Tests.Ps1
> +            $result.Test.Hosts | Should -Be "Node1"
To be sure that Variables work as expected, we should add a test where we add a few group_vars and host_vars.
See here for a small example: https://github.com/Stephanevg/psansible.inventory/blob/e755d6212886a1680c0ff22c7a583a735ae1f050/Tests/ansible.inventory.Tests.Ps1#L381-L390

2023-11-15 07:59 UTC, Stephanevg commented on psansible.inventory/psansible.inventory.psm1
> +Function Export-AnsibleInventory {
Same as mentionned in the function file. Please add comment based help

2023-11-15 07:59 UTC, Stephanevg commented on psansible.inventory/psansible.inventory.psm1
> +Function Export-AnsibleInventory {
Missing test

2023-11-15 07:59 UTC, Stephanevg commented on psansible.inventory/psansible.inventory.psm1
Could you also add a test for import-AnsibleInventory where it would point to an existing JSON inventory

2023-11-15 09:51 UTC, bateskevin commented on Code/Functions/public/Export-AnsibleInventory.ps1
Tests are already written.

2023-11-15 09:52 UTC, bateskevin commented on psansible.inventory/psansible.inventory.psm1
No, not with this PR. This is a good idea for another time tho.

2023-11-15 09:53 UTC, bateskevin commented on psansible.inventory/psansible.inventory.psm1
> +Function Export-AnsibleInventory {
Test is not missing

2024-04-12 09:47 UTC, Stephanevg approved these changes

2024-04-12 09:56 UTC, merged

2024-04-12 09:56 UTC, Stephanevg commented
As we don't have  a CI, doing this like in 1741 - Manually..

All tests pass. 69% of code coverage.
![image](https://github.com/Stephanevg/psansible.inventory/assets/6302961/acd6405e-13d1-48d4-9e24-1f715b5f4284)

We will need to do two additional things:

1. Add a CI (Tracked #11 )
2. Migrate Pester tests so they are compatible with Pester v5 (Tracked #12 )